version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:latest
  celery:
    build:
      context: .
    command: celery -A MAIN_APP worker -P eventlet
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - ./.env
volumes:
  postgres_data:
