# Generated by Django 4.1.1 on 2022-09-09 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата створення')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Дата останнього редагування')),
                ('title', models.CharField(max_length=255)),
                ('exercise', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('PG', 'In Progress'), ('RD', 'Ready'), ('CL', 'Closed'), ('OP', 'Open')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Executor')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
