# Generated by Django 4.1.1 on 2022-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('CLOSED', 'Closed'), ('OPEN', 'Open')], max_length=50),
        ),
    ]
