# Generated by Django 4.1.1 on 2022-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_author_alter_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PG', 'In_Progress'), ('RD', 'Ready'), ('CL', 'Closed'), ('OP', 'Open')], default=('AC', 'Active'), max_length=30),
        ),
    ]
