# Generated by Django 4.1.1 on 2022-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_options_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('PG', 'In Progress'), ('RD', 'Ready'), ('CL', 'Closed'), ('OP', 'Open')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
